### ISSUE TITLE
error when parsing input: unexpected end of JSON input

### ISSUE THREAD

**Issue by GregoryOrciuch** [dineshba/tf-summarize#20] opened 2022-11-30 13:33 UTC
I'm trying to fire it from CICD where I install version 0.2.2 (and tried 0.2.5 with same effect).
I took the one for linux_amd64 release build, but it fail to kind of run:

```
Plan: 0 to add, 5 to change, 0 to destroy.
─────────────────────────────────────────────────────────────────────────────
Saved the plan to: tf.plan
To perform exactly these actions, run the following command to apply:
    terraform apply "tf.plan"
$ tf-summarize tf.plan
error when parsing input: unexpected end of JSON input
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```

but that is very legit tf.plan file.

If I run it locally (when tf-summarize is installed by macos brew it works well), so it has to be something with a release thing.

Any suggestions?

**Comment by dineshba** [comment] 2022-12-02 04:50
May I know which CICD you use ? Also, how terraform is installed ?

### Reason for asking:
#### For Github actions, 
If you are using `hashicorp/setup-terraform` github action to setup terraform, ensure terraform_wrapper is set to false. Because without it, each terraform output will some extra lines. [Example](https://github.com/dineshba/tf-summarize/blob/main/.github/workflows/demo.yml#L16-L19)

Check if there is similar thing happen in your CICD setup.

**Comment by GregoryOrciuch** [comment] 2022-12-02 14:51
@dineshba 
it's a just a installation of latest terraform into the amazonlinux official docker image. 
It's something like
FROM amazonlinux2
RUN wget terraform_zip, unzip and copy to /usr/bin/
nothing there about wrapper.

I run in GitLab CI.

**Comment by everythings-gonna-be-alright** [comment] 2022-12-14 01:13
https://docs.gitlab.com/runner/shells/

`echo 'find . -type f -name "tfplan.json" -exec tf-summarize -tree {} \;' | /bin/bash`

**Comment by dineshba** [comment] 2022-12-14 13:16
Glad that we have a workaround.

I will try to reproduce this issue and understand the reason behind it. This will help me to fix this issue.

**Comment by dineshba** [comment] 2023-03-21 13:03
Hi @kayman-mk. Thanks for confirming the issue.

For the non-existing file, I am getting below error
```sh
$ tf-summarize invalid.json
error reading from input: error when opening file invalid.json: open invalid.json: no such file or directory
```
and I am in `0.2.6` version (latest version). Could you please confirm the version once ?

**Comment by Terraformadillo** [comment] 2023-07-11 16:56
@dineshba I am seeing a similar error using the latest version tag v0.3.2 installed via go.

**Comment by Terraformadillo** [comment] 2023-07-11 18:04
@dineshba Not sure if this is related bug but if I rename any working/valid tfplan to have .json extension and try to pass to tf-summarize I get following error:
`error when parsing input: invalid character 'P' looking for beginning of value`

Ex.

(venv) poliva@PhilipOlivasMBP % /Users/poliva/go/bin/tf-summarize -md tfjson

|  CHANGE  |                                                           RESOURCE                                                           |
|----------|------------------------------------------------------------------------------------------------------------------------------|
| update   | `module.client_infrastructure.module.api_zone_record[0].aws_route53_record.record`                                           |
|          | `module.client_infrastructure.module.ecs_autoscaling_target_web[0].aws_appautoscaling_target.appautoscaling_target`          |
|          | `module.client_infrastructure.module.ecs_autoscaling_target_worker[0].aws_appautoscaling_target.appautoscaling_target`       |
|          | `module.client_infrastructure.module.ecs_task_service_beat[0].aws_ecs_service.ecs_service`                                   |
|          | `module.client_infrastructure.module.ecs_task_service_web[0].aws_ecs_service.ecs_service`                                    |
|          | `module.client_infrastructure.module.ecs_task_service_worker[0].aws_ecs_service.ecs_service`                                 |
| recreate | `module.client_infrastructure.module.batch_database_restore_job_definition[0].aws_batch_job_definition.batch_job_definition` |

| CHANGE | OUTPUT |
|--------|--------|

(venv) poliva@PhilipOlivasMBP % mv tfjson tf.json

(venv) poliva@PhilipOlivasMBP % /Users/poliva/go/bin/tf-summarize -md tf.json
error when parsing input: invalid character 'P' looking for beginning of value

**Comment by GregoryOrciuch** [comment] 2023-07-11 18:19
yes, still same with 0.3.2, however point above workaround works pretty well. So you output a json plan from terraform then pipe it to tf-summarize, e.g.:
`cat tfplan.json | tf-summarize -tree'`

**Comment by Terraformadillo** [comment] 2023-07-11 18:38
@GregoryOrciuch Yeah workaround is now working for me now. I was doing something wrong with terraform show step.

**Comment by phoehnel** [comment] 2023-08-22 17:36
Got the same error with `error when parsing input: unexpected end of JSON input`  when running in GitLab CI.

When i download the exact plan file from the pipeline and run it locally using the same tf-summarize version, it works though.
Seems to be either about the CI Environment or the .deb installation method.

**Comment by stevehipwell** [comment] 2023-10-23 10:32
I'm seeing this same issue on a GitHub actions runner, I've fixed it with `jq '.' "${json_file_path}" | tf-summarize`.

**Comment by mdb** [comment] 2024-01-08 19:30
> I will try to reproduce this issue and understand the reason behind it. This will help me to fix this issue.

As a data point, I am unable to reproduce this locally on Mac OS using `tf-summarize` v0.3.6:

```
$ make summarize WORKSPACE=default
terraform show \
                -json \
                default.plan > default-plan.json
tf-summarize -v
Version: 0.3.6
tf-summarize \
                -out default-summary.md \
                -md \
                default-plan.json

Written plan summary to default-summary.md
```

However, the same command(s) and `plan` result in the following error when run from GitHub Actions's Ubuntu runner:

```
make summarize WORKSPACE=default
terraform show \
	-json \
	default.plan > default-plan.json
tf-summarize -v
Version: 0.3.6
tf-summarize \
	-out default-summary.md \
	-md \
	default-plan.json
error when parsing input: unexpected end of JSON input
```

However, passing raw JSON via STDIN works as expected both locally on Mac OS and in GitHub Actions's Ubuntu runner:

```
make summarize WORKSPACE=default
terraform show \
	-json \
	default.plan > default-plan.json
tf-summarize -v
Version: 0.3.6
jq '.' "default-plan.json" | tf-summarize \
	-md > default-summary.md
```

This suggests to me the possibility of an OS-specific bug/inconsistently related to how `tf-summarize` reads the plan JSON file if/when it's passed a plan JSON file (as opposed to when it's passed raw JSON via STDIN). Or am I barking up the wrong tree?

**Comment by mdb** [comment] 2024-01-13 18:58
👋 @dineshba I've created a quick fix for this bug via PR #64. 

I've also managed to create a reproducible demo for you over in https://github.com/dineshba/tf-summarize/pull/63, whose GitHub Actions runs encounter the `error when parsing input: unexpected end of JSON input` error: https://github.com/dineshba/tf-summarize/actions/runs/7514179482/job/20456763616#step:9:6

**Comment by mdb** [comment] 2024-03-03 20:42
@dineshba This issue was addressed in PR #64 (now merged), but never included in a [tf-summarize GitHub release](https://github.com/dineshba/tf-summarize/releases) (`tf-summarize` 0.3.7 is currently the latest release). Would you be willing to publish a 0.3.8 release that includes the PR #64 fix to this issue, then closing this issue? Thanks!

**Comment by dineshba** [comment] 2024-03-04 04:01
let me release it tomorrow with another PR merged https://github.com/dineshba/tf-summarize/pull/70

**Comment by mdb** [comment] 2024-03-06 18:47
> let me release it tomorrow with another PR merged https://github.com/dineshba/tf-summarize/pull/70

@dineshba 👋 😄 Gentle nudge: A 0.3.8 release including PR #64 and #70 would be great!

**Comment by dineshba** [comment] 2024-03-09 08:04
Created the new release v0.3.8 @mdb. Thanks for ur PRs. Really appreciated.

**Closed by dineshba** 2024-03-09 08:04 UTC
